// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99HZ9SCs5XpxqHK034BWWIPew6aMWwUU',
    appId: '1:681288317522:android:6459b06a5b63b31dc07d8b',
    messagingSenderId: '681288317522',
    projectId: 'aviato-finance',
    databaseURL: 'https://aviato-finance-default-rtdb.firebaseio.com',
    storageBucket: 'aviato-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCnKrsJlu7QawWo7miNSqpVzuH7XoH58',
    appId: '1:681288317522:ios:3e617ddd316c1872c07d8b',
    messagingSenderId: '681288317522',
    projectId: 'aviato-finance',
    databaseURL: 'https://aviato-finance-default-rtdb.firebaseio.com',
    storageBucket: 'aviato-finance.firebasestorage.app',
    androidClientId: '681288317522-b9hc8mdn376pj9j3fj9kseal6n9no4p7.apps.googleusercontent.com',
    iosClientId: '681288317522-henuf2foqmmepmuhphtjq4nolckk419i.apps.googleusercontent.com',
    iosBundleId: 'com.example.aviatoFinance',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECu03tzVXZ72Kx6lwlSJQaCven-0SjFg',
    appId: '1:681288317522:web:7b45d8335bbe5f91c07d8b',
    messagingSenderId: '681288317522',
    projectId: 'aviato-finance',
    authDomain: 'aviato-finance.firebaseapp.com',
    databaseURL: 'https://aviato-finance-default-rtdb.firebaseio.com',
    storageBucket: 'aviato-finance.firebasestorage.app',
    measurementId: 'G-T335X230JG',
  );

}